version: '3.9'

services:
  frontend:
    build: ./new-game-plus-frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build: ./new-game-plus-backend
    ports:
      - "8000:8000"
    env_file:
      - ./new-game-plus-backend/.env
